name = "newsnow"  # 你的项目名称
type = "javascript"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow_db"  # 替换为你创建的数据库名称
database_id = "c9f2fd68-64ab-4629-897a-4f6af829ac6d"      # 替换为你创建的数据库 ID
